name: C/C++ CI MacOS

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . -j 8
        shell: bash
