name: C/C++ CI ubuntu

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: build
        run: |
          sudo apt-get update && sudo apt-get install xorg-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libgl1-mesa-dev libglew-dev mesa-utils freeglut3-dev
          mkdir build
          cd build
          cmake ..
          cmake --build . -j 8
        shell: bash
